language: php
php:
  - 7.1
  - 7.0
  - hhvm

dist: xenial

matrix:
  fast_finish: true
  allow_failures:

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - "if [ `php -r 'echo (PHP_VERSION_ID < 70100 ? 0 : 1);'` -eq '1' ]; then
       echo 'new';
       composer install --verbose;
     else
       echo 'old';
       composer remove --no-update --dev friendsofphp/php-cs-fixer;
       composer remove --no-update --dev phpro/grumphp;
       composer require --no-update --verbose --dev 'phpunit/phpunit':'^6';
       composer update friendsofphp/php-cs-fixer phpunit/phpunit;
     fi"

script: vendor/bin/phpunit
