language: php
php:
  - 7.1
  - 7.0
  - hhvm

dist: xenial

matrix:
  fast_finish: true
  allow_failures:

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - "if [ `php -r 'echo (PHP_VERSION_ID < 70100 ? 0 : 1);'` -eq '1' ] then echo 'new'; else echo 'old'; composer require --no-update 'phpunit/phpunit':'^6'; fi"
  - composer install --verbose

script: vendor/bin/phpunit
