language: php
php:
  - 7.1
  - 7.0
  - hhvm

dist: xenial

matrix:
  fast_finish: true
  allow_failures:

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --verbose

script: vendor/bin/phpunit
