language: php
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

dist: xenial

matrix:
  fast_finish: true
  allow_failures:

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --verbose

script: vendor/bin/phpunit
