name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: memory_limit=-1,apc.enable_cli=1,zend.assertions=1
          php-version: "7.4"
          tools: flex

      - name: Install dependencies
        run: composer install

      - name: Psalm
        run: vendor/bin/psalm --output-format=github
