name: Unit tests

on: [push, pull_request]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        include:
          - php: '8.1'
          - php: '8.0'
          - php: '7.4'
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: memory_limit=-1,apc.enable_cli=1,zend.assertions=1
          php-version: "${{ matrix.php }}"
          tools: flex

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit --colors=always
