name: Unit tests

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        include:
          - php: '8.1'
          - php: '8.0'
          - php: '7.4'
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: memory_limit=-1,apc.enable_cli=1,zend.assertions=1
          php-version: "${{ matrix.php }}"
          tools: flex

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit --colors=always --log-junit=test-results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (PHP ${{ matrix.php }})
          path: test-results.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: tests
    runs-on: ubuntu-20.04
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
